image: node:lts

variables:
  PIPELINE: "true"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: dev
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - quality
  - test

quality:
  stage: quality
  parallel:
    matrix:
      - PROJECT_PATH: Service/AuthService
      - PROJECT_PATH: Service/ListingService
      - PROJECT_PATH: App/Admin
      - PROJECT_PATH: App/seller/backend
      - PROJECT_PATH: App/seller/frontend
      - PROJECT_PATH: App/shopper/backend
      - PROJECT_PATH: App/shopper/frontend
  script:
    - cd $PROJECT_PATH
    - npm install
    - npm run lint
    - npm run cpd

frontend-test:
  stage: test
  parallel:
    matrix:
      - PROJECT_PATH: App/Admin
      - PROJECT_PATH: App/seller/frontend
      - PROJECT_PATH: App/shopper/frontend
  script:
    - cd $PROJECT_PATH
    - npm install
    - npm test
