services:
  app:
    container_name: app
    env_file: .env
    image: cte-linux-amd64
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:3000:3000" # Admin frontend
      - "127.0.0.1:5173:5173" # Seller frontend
      - "127.0.0.1:5174:5174" # Shopper frontend
      - "127.0.0.1:3013:3013" # Seller backend
      - "127.0.0.1:3012:3012" # Shopper backend
      - "127.0.0.1:3018:3018" # Image service
      - "127.0.0.1:4000:4000" # Order service
      - "127.0.0.1:3040:3040" # Corporate backend
      - "127.0.0.1:3015:3015" # Corporate service
  postgres:
    container_name: database
    image: cte-postgres
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
