services:
  postgres:
    container_name: slug-market
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./AuthService/sql/databases.sql:/docker-entrypoint-initdb.d/1.auth.databases.sql
      - ./ListingService/sql/databases.sql:/docker-entrypoint-initdb.d/2.listing.databases.sql
      - ./OrderService/sql/databases.sql:/docker-entrypoint-initdb.d/3.order.databases.sql
      - ./CorporateService/sql/databases.sql:/docker-entrypoint-initdb.d/4.corporate.databases.sql
      - ./PaymentService/sql/databases.sql:/docker-entrypoint-initdb.d/5.payment.databases.sql
      - ./CartService/sql/databases.sql:/docker-entrypoint-initdb.d/6.cart.databases.sql
volumes:
  postgres-data:
