CREATE DATABASE cart;
\connect cart
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS cart CASCADE;
CREATE TABLE cart (
  id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE,
  items   JSONB NOT NULL DEFAULT '[]'
);

